Syntax changes

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -25,8 +25,8 @@ jobs:
       - name: Build and Test All Lessons
         run: |
           # Check if the Unity directory exists
-          if [ ! -f "lib/Unity/unity.c" ]; then
-            echo "Error: lib/Unity/unity.c not found."
+          if [ ! -f "lib/Unity/unity.h" ]; then
+            echo "Error: lib/Unity/unity.h not found."
             exit 1
           fi
           if [ ! -d "tests" ]; then
@@ -35,12 +35,12 @@ jobs:
           fi
           
           # Loop through all test files
-          for test_file in tests/test-*.c; do
+          for test_file in Tests/test-*.c; do
             executable=${test_file%.c}
             echo "Compiling $test_file..."
             
             # Compile the test file with Unity
-            gcc -o $executable $test_file ./lib/Unity/unity.c -I./lib/Unity || exit 1
+            gcc -o $executable $test_file ./lib/Unity/unity.h -I./lib/Unity || exit 1
             
             # Run the compiled test executable
             echo "Running $executable..."
